### PR TITLE
MultiDcSpec: Get free ports on the correct interface

### LINKED ISSUE #446: Failed: MultiDcSpec
```
[info] MultiDcSpec:
[info] Http cluster management
[info] - must allow multiple DCs *** FAILED *** (17 milliseconds)
[info]   java.net.BindException: Cannot assign requested address
[info]   at sun.nio.ch.Net.bind0(Native Method)
[info]   at sun.nio.ch.Net.bind(Net.java:433)
[info]   at sun.nio.ch.Net.bind(Net.java:425)
[info]   at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
[info]   at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
[info]   at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67)
[info]   at akka.testkit.SocketUtil$$anonfun$temporaryServerAddresses$2.apply(SocketUtil.scala:93)
```

https://travis-ci.org/akka/akka-management/jobs/479754894

There was no other information in the logs in case travis removes the logs

### PR DESCRIPTION
**Pull request by chbatey**
Fixes #446

### CODE REVIEW

File: cluster-http/src/test/scala/akka/management/cluster/MultiDcSpec.scala [hunk 1]
```diff
@@ -59,7 +59,7 @@ class MultiDcSpec
       implicit val materializer = ActorMaterializer()
 
       val routeSettings =
-        ManagementRouteProviderSettings(selfBaseUri = s"http://126.0.0.1:$httpPortA", readOnly = false)
+        ManagementRouteProviderSettings(selfBaseUri = s"http://127.0.0.1:$httpPortA", readOnly = false)
```
Comment (raboof) [inline cluster-http/src/test/scala/akka/management/cluster/MultiDcSpec.scala]: huh, how did that work?

Comment (chbatey) [reply cluster-http/src/test/scala/akka/management/cluster/MultiDcSpec.scala]: that is only used for links it gives out (i think)
